apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-redis
          image: redis:7.0.9
          command:
            - bash
            - "-c"
            - |
              set -ex
              HOSTNAME=$(hostname)
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/config-map/master.conf /etc/redis.conf
              else
                cp /mnt/config-map/replica.conf /etc/redis.conf
              fi
              sed -i "s/\$HOST/$HOSTNAME/g" /etc/redis.conf
          volumeMounts:
            - name: conf
              mountPath: /etc
              subPath: redis.conf
            - name: config
              mountPath: /mnt/config-map
      containers:
        - name: redis
          image: redis:7.0.9
          command:
            - redis-server
          args:
            - /etc/redis.conf
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
              name: redis-tcp
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
              readOnly: false
            - name: conf
              mountPath: /etc/
              subPath: redis.conf
      volumes:
        - name: conf
          emptyDir:
            sizeLimit: 100Mi
        - name: config
          configMap:
            name: redis
        - name: redis-data
          emptyDir:
            sizeLimit: 500Mi
