apiVersion: v1
kind: Service
metadata:
  name: sentinel
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
  clusterIP: None
  selector:
    app: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-0
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
  selector:
    app: sentinel
    statefulset.kubernetes.io/pod-name: sentinel-0
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-1
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
  selector:
    app: sentinel
    statefulset.kubernetes.io/pod-name: sentinel-1
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-2
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
  selector:
    app: sentinel
    statefulset.kubernetes.io/pod-name: sentinel-2