apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel
data:
  sentinel.conf: |
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel announce-ip $HOST
    sentinel announce-port 6379
    sentinel monitor mymaster redis-0 6379 2
    sentinel down-after-milliseconds mymaster 60000
    sentinel failover-timeout mymaster 180000
    sentinel parallel-syncs mymaster 1