apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
spec:
  selector:
    matchLabels:
      app: sentinel
  serviceName: sentinel
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-sentinel
          image: redis:7.0.9
          command:
            - bash
            - "-c"
            - |
              set -ex
              HOSTNAME=$(hostname)
              cp /mnt/config-map/sentinel.conf /etc/sentinel.conf
              sed -i "s/\$HOST/$HOSTNAME/g" /etc/sentinel.conf
          volumeMounts:
            - name: conf
              mountPath: /etc
              subPath: sentinel.conf
            - name: config
              mountPath: /mnt/config-map
      containers:
        - name: sentinel
          image: redis:7.0.9
          command:
            - redis-server
          args:
            - /etc/sentinel.conf
            - --sentinel
          ports:
            - containerPort: 26379
              name: sentinel-tcp
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /etc/
              subPath: sentinel.conf
      volumes:
        - name: conf
          emptyDir:
            sizeLimit: 100Mi
        - name: config
          configMap:
            name: sentinel