# Default values for redis-sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: redis-sentinel
redis:
  image:
    repository: redis
    tag: "7.0.9"
    pullPolicy: IfNotPresent
  replicaCount: 3

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

sentinel:
  image:
    repository: redis
    tag: "7.0.9"
    pullPolicy: IfNotPresent
  replicaCount: 3

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}