apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  master.conf: |
    port 6379
    replica-announce-ip $HOST
  replica.conf: |
    port 6379
    replicaof $MASTER 6379
    replica-announce-ip $HOST