apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      protocol: TCP
      targetPort: redis-tcp
      name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - nodePort: 30005
      port: 6379
      protocol: TCP
      targetPort: redis-tcp
      name: redis
  selector:
    app: redis