apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      protocol: TCP
      targetPort: redis-tcp
      name: redis
  selector:
    app: redis
{{- range $index := until ( .Values.redis.replicaCount | int ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ $index }}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: redis-tcp
      name: redis
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-{{ $index }}
{{- end }}