apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
data:
  replica.conf: |
    port 6379
    enable-debug-command yes
  ping.sh: |
    set -ex
    redis-cli ping