---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: {{ .Values.redis.replicaCount }}
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: redis
    spec:
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - bash
            - "-c"
            - |
              set -ex
              HOSTNAME=$(hostname)
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/config-map/master.conf /etc/redis.conf
              else
                cp /mnt/config-map/replica.conf /etc/redis.conf
              fi
              sed -i "s/\$HOST/$HOSTNAME/g" /etc/redis.conf
          volumeMounts:
            - name: conf
              mountPath: /etc
              subPath: redis.conf
            - name: config
              mountPath: /mnt/config-map
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
          args:
            - /etc/redis.conf
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
              name: redis-tcp
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
              readOnly: false
            - name: conf
              mountPath: /etc/
              subPath: redis.conf
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: conf
          emptyDir:
            sizeLimit: 100Mi
        - name: config
          configMap:
            name: redis
        - name: redis-data
          emptyDir:
            sizeLimit: 500Mi
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
