apiVersion: v1
kind: Service
metadata:
  name: sentinel
  labels:
    app: sentinel
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 46379
      protocol: TCP
      targetPort: sentinel-tcp
      name: sentinel
  selector:
    app: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-nodeport
  labels:
    app: sentinel
spec:
  type: NodePort
  ports:
    - nodePort: 30006
      port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
      name: sentinel
  selector:
    app: sentinel
{{- range $index := until ( .Values.sentinel.replicaCount | int ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-{{ $index }}
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
    - port: 26379
      protocol: TCP
      targetPort: sentinel-tcp
      name: sentinel
  selector:
    app: sentinel
    statefulset.kubernetes.io/pod-name: sentinel-{{ $index }}
{{- end }}