apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel
  namespace: {{ .Values.namespace }}
data:
  sentinel.conf: |
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    protected-mode no
    sentinel announce-port 26379
    sentinel down-after-milliseconds mymaster 30000
    sentinel failover-timeout mymaster 180000
    sentinel parallel-syncs mymaster 1
  ping.sh: |
    set -ex
    redis-cli -p 26379 ping
